name: Automated Tests for find_lowest_number.py

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Convert line endings to LF
        run: |
          dos2unix test_data/test1_expected.txt
          dos2unix test_data/test2_expected.txt
          dos2unix test_data/test3_expected.txt
          dos2unix test_result1.txt
          dos2unix test_result2.txt
          dos2unix test_result3.txt

      - name: Run Test 1
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_result1.txt
          diff test_result1.txt test_data/test1_expected.txt

      - name: Run Test 2
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test_result2.txt
          diff test_result2.txt test_data/test2_expected.txt

      - name: Run Test 3
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test_result3.txt
          diff test_result3.txt test_data/test3_expected.txt
