name: Automated Tests for find_lowest_number.py

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run Tests
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_result1.txt
          diff output1.txt test_data/test1_expected.txt
          
          python3 find_lowest_number.py test_data/test2_input.txt test_result2.txt
          diff output2.txt test_data/test2_expected.txt
          
          python3 find_lowest_number.py test_data/test3_input.txt test_result3.txt
          diff output3.txt test_data/test3_expected.txt
